### ISSUE TITLE
アイコンなしでサインアップするとエラーページに遷移する

### ISSUE THREAD

**Issue by norotime** [watepu/dokkan#1]
問題：
![2018-10-28 11 17 18](https://user-images.githubusercontent.com/7435505/47611162-16b0a580-daa3-11e8-8e18-a98e077fa99f.png)

対策案：
アイコンなしでも正常にサインアップされるようにする
（律儀に最初から画像登録する人は少ないため）

**Comment by watepu** [comment]
usersのimageにつけたnull: falseを削除して対応しました
